#!/usr/bin/env node
// fetch-icons.mjs
// Scans src/ for <icon-plus name="X"> usages, fetches company icons from the
// IconPlus API (getConfig → getIconInfo → getIcon×2), and generates dual-theme
// (light/dark) SVG files + barrel index.js under src/assets/icons/.
//
// Fallback flow: names not found in the API (or when unreachable) stay absent
// from the barrel — the icon-plus.vue wrapper then falls back to the SweetUI
// built-in font icon (sweetui-icon-{name}-l).
//
// Usage:
//   node fetch-icons.mjs --dir "<artifact-folder>/<slug>" [--base-url <url>] [--timeout <ms>]
//
// Output (agent-parseable):
//   RESULT: OK
//   RESOLVED: <n>, MISSED: <m>, CACHED: <c>
//   MISSED_LIST: <comma-separated, omitted if empty>
//   ICONS_DIR: <absolute path>
//   RESULT: FAIL | <reason>

import { existsSync, readFileSync, writeFileSync, readdirSync, mkdirSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- CLI args ---
const args = process.argv.slice(2);
function getOpt(long, short) {
  const idx = args.findIndex((a) => a === long || a === short);
  if (idx === -1) return undefined;
  const val = args[idx + 1];
  if (val === undefined || val.startsWith('-')) return undefined;
  return val;
}

const dir = getOpt('--dir', '-d');
if (!dir) {
  console.log('RESULT: FAIL | Usage: node fetch-icons.mjs --dir "<folder with src/>" [--base-url <url>] [--timeout <ms>]');
  process.exit(1);
}

const baseUrl = (getOpt('--base-url') || 'https://octo.hdesign.huawei.com').replace(/\/+$/, '');
const timeoutMs = parseInt(getOpt('--timeout') || '10000', 10);

const root = resolve(dir);
const srcDir = join(root, 'src');
if (!existsSync(srcDir)) {
  console.log(`RESULT: FAIL | src folder not found: ${srcDir}`);
  process.exit(1);
}

// ============================================================
// 1. Usage scanning + dedup: <icon-plus name="X"> across .vue/.js
// ============================================================

function walkFiles(dirPath, exts, out = []) {
  for (const entry of readdirSync(dirPath, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    if (entry.name === 'assets' && dirPath === srcDir) {
      // skip assets/icons (our own output) to avoid self-reference
      const iconsDir = join(dirPath, 'assets', 'icons');
      if (existsSync(iconsDir)) continue;
    }
    const full = join(dirPath, entry.name);
    if (entry.isDirectory()) walkFiles(full, exts, out);
    else if (exts.includes(entry.name.slice(entry.name.lastIndexOf('.')))) out.push(full);
  }
  return out;
}

const vueAndJsFiles = walkFiles(srcDir, ['.vue', '.js']);
const iconNames = new Set();
const usageRe = /<icon-plus\b[^>]*\bname=["']([^"']+)["']/g;
for (const file of vueAndJsFiles) {
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(usageRe)) {
    iconNames.add(m[1]);
  }
}

const iconList = [...iconNames].sort();

if (iconList.length === 0) {
  console.log('RESULT: OK');
  console.log('RESOLVED: 0, MISSED: 0');
  console.log(`ICONS_DIR: ${resolve(join(srcDir, 'assets', 'icons'))}`);
  process.exit(0);
}

// ============================================================
// 1.5. Incremental cache: names whose .light.svg + .dark.svg pair
//      already on disk are skipped entirely (no network, files
//      untouched) — confirmed icons never drift on re-runs.
// ============================================================

const iconsDir = join(srcDir, 'assets', 'icons');

// Barrel is rebuilt from a plain name list; the .svg files must already be on
// disk for every name passed in. Deterministic: sorted names, fixed template.
// The wrapper (icon-plus.vue) imports { icons } from this barrel; names absent
// from the barrel fall back to the SweetUI font icon inside the wrapper.
function writeBarrel(resolvedNames) {
  const entries = resolvedNames
    .map((name) => `  ${JSON.stringify(name)}: { light: ${JSON.stringify('./' + name + '.light.svg')}, dark: ${JSON.stringify('./' + name + '.dark.svg')} }`)
    .sort();

  const barrelContent = `// AUTO-GENERATED by fetch-icons.mjs — do not edit
// Company icon+ barrel: semantic name → dual-theme (light/dark) SVG urls.
// icon-plus.vue consults this map first; a miss falls back to the SweetUI
// built-in font icon (sweetui-icon-{name}-l).
export const icons = {
${entries.join(',\n')}
};

// CSS: light visible by default, dark visible when body[theme] is not default
if (typeof document !== 'undefined' && !document.getElementById('swt-icon-pair-style')) {
  var style = document.createElement('style')
  style.id = 'swt-icon-pair-style'
  style.textContent = [
    '.swt-icon-pair .swt-icon-dark { display: none }',
    'body[theme="dark"] .swt-icon-pair .swt-icon-light { display: none }',
    'body[theme="dark"] .swt-icon-pair .swt-icon-dark { display: block }'
  ].join('\\n')
  document.head.appendChild(style)
}
`;

  mkdirSync(iconsDir, { recursive: true });
  writeFileSync(join(iconsDir, 'index.js'), barrelContent, 'utf8');
}

function hasCachedPair(name) {
  return (
    existsSync(join(iconsDir, `${name}.light.svg`)) &&
    existsSync(join(iconsDir, `${name}.dark.svg`))
  );
}

const cachedNames = iconList.filter(hasCachedPair);
const netNames = iconList.filter((n) => !hasCachedPair(n));

if (netNames.length === 0) {
  // All requested names already on disk: rebuild barrel from disk, no requests.
  writeBarrel(cachedNames.slice().sort());
  console.log('RESULT: OK');
  console.log(`RESOLVED: ${cachedNames.length}, MISSED: 0, CACHED: ${cachedNames.length}`);
  console.log(`ICONS_DIR: ${resolve(iconsDir)}`);
  process.exit(0);
}

// ============================================================
// 2. Connectivity check + API
// ============================================================

async function fetchWithTimeout(url, ms) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

// --- connectivity probe (5s): returns parsed config, or null when unreachable ---
// probe and main-flow share the same getConfig endpoint; the parsed response is
// reused as the config so a slow-but-alive server is not killed by a tight probe.
async function probeConfig() {
  try {
    return await fetchWithTimeout(`${baseUrl}/assetRepository/iconPlus/getConfig`, 5000);
  } catch {
    return null;
  }
}

async function apiGetIconInfo(keywords, topK = 5, sourceId = 6, groupId = '74,77,93') {
  const params = new URLSearchParams({
    keyword: keywords,
    topK: String(topK),
    source_id: String(sourceId),
    group_id: groupId,
  });
  return fetchWithTimeout(`${baseUrl}/assetRepository/iconPlus/getIconInfo?${params}`, timeoutMs);
}

async function apiGetIcon(urls, theme, color, size, style, names, categories, fileType = 'svg') {
  const params = new URLSearchParams({ url: urls, theme, color, size, style, fileType });
  if (names) params.set('name', names);
  if (categories) params.set('category', categories);
  return fetchWithTimeout(`${baseUrl}/assetRepository/iconPlus/getIcon?${params}`, timeoutMs);
}

function selectConfigDefaults(config) {
  const size = config.size?.find((s) => s.key === '24')?.key || config.size?.[0]?.key || '24';
  const styleValue = config.style?.find((s) => s.key === 'border')?.value || config.style?.[0]?.value || '线性';
  const lightColor =
    config.colors?.find((c) => c.style === styleValue)?.id || config.colors?.[0]?.id || '';
  const darkColor =
    config.dark_colors?.find((c) => c.style === styleValue)?.id || config.dark_colors?.[0]?.id || lightColor;
  return { size, style: styleValue, lightColor, darkColor };
}

// ============================================================
// 3. Main flow
// ============================================================

// --- 3a. Connectivity probe: unreachable → net miss, keep SW font fallback + cached ---
const config = await probeConfig();
if (!config) {
  writeBarrel(cachedNames.slice().sort());
  console.log('RESULT: OK');
  console.log(`RESOLVED: ${cachedNames.length}, MISSED: ${netNames.length}, CACHED: ${cachedNames.length}`);
  console.log(`MISSED_LIST: ${netNames.join(', ')}`);
  console.log(`ICONS_DIR: ${resolve(iconsDir)}`);
  process.exit(0);
}

// --- 3b. Intranet: IconPlus remaining API (probe response already carries config) ---
try {
  const { size, style, lightColor, darkColor } = selectConfigDefaults(config);

  // Step 2: getIconInfo (batch search the not-yet-cached names)
  const searchResults = await apiGetIconInfo(netNames.join(','), 5);
  // Match by englishName (case-insensitive), fall back to highest score
  const nameToUrl = new Map(); // semantic name → company icon url
  const urlToMeta = new Map(); // company icon url → { name, category }

  const resultsArray = Array.isArray(searchResults) ? searchResults : [searchResults];
  for (const group of resultsArray) {
    const keyword = group.keyword;
    const candidates = (group.icons || []).filter((i) => i.url);
    if (candidates.length === 0) continue;
    const exact = candidates.find(
      (i) => i.englishName && i.englishName.toLowerCase() === keyword.toLowerCase(),
    );
    const best =
      exact || [...candidates].sort((a, b) => (b.score || 0) - (a.score || 0))[0];
    if (best && best.url) {
      nameToUrl.set(keyword, best.url);
      if (!urlToMeta.has(best.url)) {
        urlToMeta.set(best.url, { name: best.name || '', category: best.category || '' });
      }
    }
  }

  const hitNames = [...nameToUrl.keys()];
  const missedNames = netNames.filter((n) => !nameToUrl.has(n));

  if (hitNames.length === 0) {
    // Nothing new resolved: barrel rebuilt from cached files only (deterministic).
    if (cachedNames.length) writeBarrel(cachedNames.slice().sort());
    console.log('RESULT: OK');
    console.log(`RESOLVED: ${cachedNames.length}, MISSED: ${missedNames.length}, CACHED: ${cachedNames.length}`);
    if (missedNames.length) console.log(`MISSED_LIST: ${missedNames.join(', ')}`);
    console.log(`ICONS_DIR: ${resolve(iconsDir)}`);
    process.exit(0);
  }

  // Step 3: getIcon × 2 (light + dark, parallel — independent requests)
  const allUrls = [...urlToMeta.keys()].join(',');
  const allNames = [...urlToMeta.values()].map((m) => m.name).filter(Boolean).join(',');
  const allCategories = [...new Set([...urlToMeta.values()].map((m) => m.category).filter(Boolean))].join(',');
  const urlToLightSvg = new Map();
  const urlToDarkSvg = new Map();

  const [lightSettled, darkSettled] = await Promise.allSettled([
    apiGetIcon(allUrls, 'light', lightColor, size, style, allNames, allCategories),
    apiGetIcon(allUrls, 'dark', darkColor, size, style, allNames, allCategories),
  ]);

  if (lightSettled.status === 'fulfilled') {
    const lightArr = Array.isArray(lightSettled.value) ? lightSettled.value : [lightSettled.value];
    for (const item of lightArr) {
      if (item.url && item.data) urlToLightSvg.set(item.url, item.data);
    }
  }

  if (darkSettled.status === 'fulfilled') {
    const darkArr = Array.isArray(darkSettled.value) ? darkSettled.value : [darkSettled.value];
    for (const item of darkArr) {
      if (item.url && item.data) urlToDarkSvg.set(item.url, item.data);
    }
  }

  // ============================================================
  // 4. Write .svg files for new hits + rebuild barrel (cached ∪ new)
  // ============================================================

  mkdirSync(iconsDir, { recursive: true });

  function processSvg(svgString) {
    let svg = String(svgString).replace(/^﻿/, '').trim();
    const tagMatch = svg.match(/<svg\b[^>]*>/i);
    if (tagMatch) {
      const originalTag = tagMatch[0];
      const cleanedTag = originalTag
        .replace(/\s+width\s*=\s*["'][^"']*["']/gi, '')
        .replace(/\s+height\s*=\s*["'][^"']*["']/gi, '')
        .replace(/<svg\b/i, '<svg width="1em" height="1em"');
      svg = svg.replace(originalTag, cleanedTag);
    } else {
      svg = `<svg width="1em" height="1em" xmlns="http://www.w3.org/2000/svg">${svg}</svg>`;
    }
    return svg;
  }

  const newlyResolved = [];

  for (const name of hitNames) {
    const url = nameToUrl.get(name);
    const lightSvg = urlToLightSvg.get(url);
    const darkSvg = urlToDarkSvg.get(url) || lightSvg; // dark miss → reuse light

    if (!lightSvg) continue; // total miss (light failed too) → skip, SW fallback

    newlyResolved.push(name);

    writeFileSync(join(iconsDir, `${name}.light.svg`), processSvg(lightSvg), 'utf8');
    writeFileSync(join(iconsDir, `${name}.dark.svg`), processSvg(darkSvg), 'utf8');
  }

  const resolvedNames = cachedNames.concat(newlyResolved).sort();
  writeBarrel(resolvedNames);

  // Output
  const finalMissed = iconList.filter((n) => !resolvedNames.includes(n));
  console.log('RESULT: OK');
  console.log(`RESOLVED: ${resolvedNames.length}, MISSED: ${finalMissed.length}, CACHED: ${cachedNames.length}`);
  if (finalMissed.length) console.log(`MISSED_LIST: ${finalMissed.join(', ')}`);
  console.log(`ICONS_DIR: ${resolve(iconsDir)}`);
  process.exit(0);
} catch (e) {
  console.log(`RESULT: FAIL | ${e.message}`);
  process.exit(1);
}
