import { defineConfig, globalIgnores } from 'eslint/config';
import tsParser from '@typescript-eslint/parser';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import vueParser from 'vue-eslint-parser';
import globals from 'globals';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// 规则集迁移自 3d-templete（用户要求遵循其 eslint 定义），适配本项目目录结构。
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const compatConfigs = compat.extends(
  'eslint:recommended',
  'plugin:@typescript-eslint/recommended',
);

// TS 与 JS 共用的风格/质量规则（迁移自 3d-templete，两处 rules 中相同的键值）。
const sharedRules = {
  'no-return-assign': 'warn',
  'no-useless-concat': 'warn',
  'no-eq-null': 'warn',
  'no-useless-call': 2,
  'no-else-return': 'warn',
  'array-callback-return': 'error',
  'no-self-compare': 'warn',
  'no-empty': 'warn',
  'no-sequences': 'error',
  'no-useless-computed-key': 'error',
  'no-constant-condition': 'error',
  'no-loss-of-precision': 'off',
  'space-infix-ops': 'error',
  'no-trailing-spaces': 'warn',
  quotes: ['warn', 'single'],
  'no-eval': 'error',
  'no-implied-eval': 'error',
  'no-script-url': 'error',
  'no-extend-native': 'error',
  'no-proto': 'error',
  'no-new-func': 'error',
  'new-cap': 'warn',
  'id-length': ['warn', { max: 40, min: 1 }],
  camelcase: 'off',
  'no-shadow-restricted-names': 'error',
  'no-magic-numbers': ['off', { ignoreArrayIndexes: true, ignore: [-1, 0, 1, 2, 3, 4, 5, 8] }],
  'multiline-comment-style': ['error', 'separate-lines'],
  'line-comment-position': ['warn', { position: 'above' }],
  'lines-around-comment': ['error', { beforeBlockComment: true, beforeLineComment: false, allowBlockStart: true }],
  'spaced-comment': ['error', 'always'],
  'no-warning-comments': ['off', { terms: ['TODO', 'FIXME', 'DTS'], location: 'anywhere' }],
  indent: ['warn', 2, { SwitchCase: 1 }],
  'max-len': ['warn', { code: 120, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true }],
  'brace-style': 'error',
  'keyword-spacing': ['error', { before: true }],
  'space-before-function-paren': ['off', 'always'],
  'no-multi-spaces': 'error',
  curly: 'error',
  'no-var': 'error',
  'one-var': ['error', 'never'],
  'no-multi-assign': 'warn',
  'no-undef-init': 'error',
  'no-new-object': 'error',
  'no-param-reassign': ['warn', { props: false }],
  'prefer-rest-params': 'error',
  'prefer-arrow-callback': 'error',
  'arrow-parens': ['error', 'always'],
  'arrow-body-style': ['error', 'as-needed'],
  'consistent-return': 'warn',
  'no-this-before-super': 'error',
  'prefer-template': 'error',
  'prefer-destructuring': ['off', { array: true, object: true }],
  'dot-notation': 'warn',
  'accessor-pairs': 'warn',
  'no-prototype-builtins': 'error',
  'guard-for-in': 'warn',
  'no-nested-ternary': 'warn',
  'default-case': 'warn',
  'no-fallthrough': 'error',
  'no-case-declarations': 2,
  'no-duplicate-imports': 'warn',
  'no-floating-decimal': 'error',
  'use-isnan': 2,
  'no-unsafe-finally': 'error',
  'no-return-await': 'error',
  'no-with': 'error',
  'no-console': 'off',
  'no-alert': 'error',
  'no-debugger': 'error',
  'no-implicit-coercion': 'warn',
  'no-useless-return': 'error',
  'function-paren-newline': ['warn', 'multiline'],
  'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
  'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 4 }],
  'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
  'padded-blocks': ['off', { classes: 'never' }],
  'no-multiple-empty-lines': ['warn', { max: 1 }],
  'object-curly-spacing': ['warn', 'always'],
  'array-bracket-spacing': ['warn', 'never'],
  'comma-dangle': ['warn', 'always-multiline'],
  semi: ['warn', 'always'],
  'comma-spacing': ['warn', { before: false, after: true }],
  'max-lines': ['warn', 2000],
  'max-lines-per-function': ['warn', { max: 100 }],
  complexity: ['warn', 30],
  'max-depth': ['warn', 5],
  'max-nested-callbacks': ['error', 4],
  'max-params': ['warn', 5],
  'func-style': ['warn', 'expression', { allowArrowFunctions: true }],
  eqeqeq: 'warn',
  'no-unexpected-multiline': 'warn',
  'no-negated-condition': 'warn',
  'no-mixed-operators': ['warn', {
    groups: [
      ['&', '|', '^', '~', '<<', '>>', '>>>'],
      ['==', '!=', '===', '!==', '>', '>=', '<=', '<'],
      ['&&', '||'],
      ['in', 'instanceof'],
    ],
    allowSamePrecedence: true,
  }],
  'no-implicit-globals': 'warn',
  'no-throw-literal': 'warn',
  'prefer-promise-reject-errors': 'warn',
  'no-continue': 'warn',
  'vars-on-top': 'warn',
  strict: ['warn', 'function'],
  'no-new': 'error',
  'no-useless-escape': 'warn',
  'prefer-const': 'off',
  'no-unused-vars': 'off',
  'no-tabs': 'error',
  'no-empty-function': 'off',
  'no-duplicate-case': 2,
  'no-mixed-spaces-and-tabs': ['error'],
  'eol-last': 'error',
  'object-curly-newline': ['warn', {
    ObjectExpression: { multiline: true, minProperties: 4 },
    ObjectPattern: { multiline: true, minProperties: 4 },
    ImportDeclaration: { multiline: true, minProperties: 4 },
    ExportDeclaration: { multiline: true, minProperties: 4 },
  }],
  'quote-props': ['error', 'as-needed'],
  'key-spacing': ['error'],
  'space-before-blocks': ['error'],
  'semi-spacing': ['error', { before: false, after: true }],
  'arrow-spacing': ['error'],
  'space-in-parens': ['error', 'never'],
  'no-useless-assignment': 'warn',
};

export default defineConfig([
  ...compatConfigs,

  // TypeScript 主配置
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { legacyDecorators: true, module: true },
        allowImportExportEverywhere: true,
        requireConfigFile: false,
        project: './tsconfig.app.json',
        tsconfigRootDir: __dirname,
        extraFileExtensions: ['.vue'],
        warnOnUnsupportedTypeScriptVersion: false,
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: { '@typescript-eslint': typescriptEslint },
    linterOptions: { reportUnusedDisableDirectives: 'warn' },
    rules: {
      ...sharedRules,
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'warn',
      '@typescript-eslint/naming-convention': [
        'warn',
        { selector: 'default', format: ['camelCase'], leadingUnderscore: 'allow', trailingUnderscore: 'allow' },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'variable', format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'import', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
        { selector: 'variable', modifiers: ['const'], format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'property', format: ['camelCase', 'PascalCase', 'UPPER_CASE'], leadingUnderscore: 'allow' },
        { selector: 'accessor', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
      ],
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': [1, { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-interface': 'warn',
      '@typescript-eslint/no-use-before-define': ['warn'],
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/prefer-for-of': 'warn',
      '@typescript-eslint/no-var-requires': 'error',
      '@typescript-eslint/consistent-type-imports': ['warn', {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
      }],
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-nocheck': true, 'ts-check': false, 'ts-expect-error': 'allow-with-description', 'ts-ignore': 'allow-with-description' }],
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
    },
  },

  // Vue SFC：vue-eslint-parser 外壳 + script 内容交给 TS parser
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        parser: tsParser,
        ecmaFeatures: { legacyDecorators: true },
        requireConfigFile: false,
        project: './tsconfig.app.json',
        tsconfigRootDir: __dirname,
        extraFileExtensions: ['.vue'],
        warnOnUnsupportedTypeScriptVersion: false,
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: { '@typescript-eslint': typescriptEslint },
    rules: {
      ...sharedRules,
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'warn',
      '@typescript-eslint/naming-convention': [
        'warn',
        { selector: 'default', format: ['camelCase'], leadingUnderscore: 'allow', trailingUnderscore: 'allow' },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'variable', format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'import', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
        { selector: 'variable', modifiers: ['const'], format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'property', format: ['camelCase', 'PascalCase', 'UPPER_CASE'], leadingUnderscore: 'allow' },
        { selector: 'accessor', format: ['camelCase', 'PascalCase', 'UPPER_CASE'] },
      ],
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': [1, { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/consistent-type-imports': ['warn', {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
      }],
    },
  },

  // JavaScript 配置
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    linterOptions: { reportUnusedDisableDirectives: 'warn' },
    rules: {
      ...sharedRules,
      'no-undef': 'error',
      'no-shadow': 'error',
      'no-magic-numbers': ['warn', { ignoreArrayIndexes: true, ignore: [-1, 0, 1, 2, 3, 4, 5, 8] }],
      'no-unused-vars': ['warn', { vars: 'all', args: 'after-used', ignoreRestSiblings: true }],
      'no-empty-function': 'warn',
      'no-console': 'error',
    },
  },

  // scripts/ CLI 工具（冒烟/模型生成）：console 是输出接口，魔数是二进制协议常量
  {
    files: ['scripts/**/*.mjs'],
    rules: {
      'no-console': 'off',
      'no-magic-numbers': 'off',
      'line-comment-position': 'off',
      'id-length': 'off',
    },
  },

  // 配置文件覆盖
  {
    files: ['*.config.js', '*.config.ts', '*.config.mjs', '.*rc.js'],
    rules: {
      'no-magic-numbers': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'no-console': 'off',
      '@typescript-eslint/naming-convention': 'off',
    },
  },

  // 忽略文件配置
  globalIgnores([
    '**/*.d.ts',
    'dist/',
    'build/',
    'coverage/',
    'node_modules/',
    '.git/',
    '*.min.js',
    '**/__tests__/fixtures/**',
    '**/__mocks__/**',
    'docs/',
    'eslint.config.mjs',
    'vite.config.ts',
    '*.json',
  ]),
]);
