#!/usr/bin/env node
// generate-css.mjs — tokens.json → frontend/element-plus/tokens/*.css
//
// 管线第二步：library/tokens.json（extract 产物，gts-flat-dtcg schema）
//   → 本脚本 → frontend/element-plus/tokens/ 七件（init 原样拷给工作区）
//
// 产物（替换旧 12 件为 7 件）：
//   index.css          入口 @import
//   primitive.css      基础色板/尺寸/字体/阴影/边框字面值
//   semantic.css       语义 var() 链（--color-*，浅色为默认主题）
//   charts.css         图表六色 + 无障碍 + 延展组合（data-chart-palette 切换）
//   code.css           代码高亮（浅色默认 + data-theme="dark"）
//   frost.css          毛玻璃 token + 规则层（种子值来自 extract 回填）
//   element-plus.css   bridge：--el-* → --color-*（手写一次不再动的锚点，脚本只核对不生成规则段）
//
// 不再产出（旧集退役项，第 10 步删除）：
//   semantic-dark.css  旧深色语义映射是工程自造值，GTS 2.2 深色 UI 未定义；data-theme="dark"
//                      协议位保留，code/frost/border-width 有真源深色值照发
//   glass.css          旧 aurora-glass 遗留，新包 frost 体系统一
//   component.css + components/*.css   g-* 兼容层：patterns 迁移（第 5 步）换新名后退役
//   frost-decoration.css               并入 frost.css（装饰参数进种子）
//
// Usage:
//   node generate-css.mjs --tokens <tokens.json> --out <tokens-dir> [--check-only]

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import path from 'node:path';

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i].startsWith('--')) args[argv[i].slice(2)] = argv[i + 1], i++;
  }
  return args;
}

const HEADER = (src) =>
  `/* GENERATED by scripts/generate-css.mjs from library/tokens.json (${src}). Do not edit — re-run the pipeline. */\n`;

// ---------- helpers ----------
const v = (t) => t.$value;
const cssRef = (name) => `var(--${name})`;

function shadowCss(sh) {
  return `${sh.offsetX} ${sh.offsetY} ${sh.blur} ${sh.spread} ${sh.color}`;
}

function fontFamilyCss(stack) {
  return stack.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
}

// DTCG {alias} → var(--alias)
function resolveCss(value, tokens) {
  if (typeof value === 'string') {
    const m = value.match(/^\{(.+)\}$/);
    return m ? cssRef(m[1]) : value;
  }
  if (Array.isArray(value)) return fontFamilyCss(value);
  if (typeof value === 'object' && value.offsetX) return shadowCss(value);
  return String(value);
}

// 语义色：纯色出 var() 链；透明叠加（gts.ref + $value 为 rgba 字面值）出 rgba(var(--ref) 字面) 不可能——
// CSS 无法对 var() 做 alpha 合成（color-mix 可但兼容面窄），与旧库一致：透明叠加直接落 rgba 字面值，
// gts.ref/alpha 只作审计。此决策与旧 semantic-light.css 行为一致。
function semanticLine(name, t) {
  const raw = typeof t.$value === 'string' && /^\{.+\}$/.test(t.$value)
    ? cssRef(t.$value.slice(1, -1))
    : t.$value;
  return `  --${name}: ${raw};`;
}

// ---------- primitive.css ----------
function genPrimitive(tokens, sourceVersion) {
  const L = [];
  const order = ['palette', 'dimension', 'shadow', 'fontFamily', 'fontWeight', 'strokeStyle'];
  const bucket = Object.fromEntries(order.map((k) => [k, []]));
  for (const [name, t] of Object.entries(tokens)) {
    if (t.$extensions?.gts?.source === 'backfill-g1.5.1') continue; // frost 种子走 frost.css
    if (t.$extensions?.gts?.hljs) continue;                          // code-* 走 code.css
    const type = t.$type === 'dimension' ? 'dimension'
      : t.$type === 'shadow' ? 'shadow'
      : t.$type === 'fontFamily' ? 'fontFamily'
      : t.$type === 'fontWeight' ? 'fontWeight'
      : t.$type === 'strokeStyle' ? 'strokeStyle'
      : t.$type === 'color' ? 'palette' : null;
    if (!type) continue;
    // 语义色属于 semantic.css（$extensions.gts.description 且名字以 color- 开头的纯语义层）
    if (type === 'palette' && name.startsWith('color-') && !name.startsWith('color-chart')) continue;
    if (type === 'palette' && name.startsWith('company-')) { bucket.palette.push([name, t]); continue; }
    bucket[type].push([name, t]);
  }

  L.push(HEADER(sourceVersion));
  L.push(`/* 基础层：字面值。来源=GTS 2.2 设计系统.md；语义层（semantic.css）以 var() 引用本层。 */`);
  L.push(`:root {`);
  for (const [name, t] of bucket.palette) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  for (const [name, t] of bucket.dimension) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  for (const [name, t] of bucket.fontFamily) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  for (const [name, t] of bucket.fontWeight) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  for (const [name, t] of bucket.strokeStyle) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  for (const [name, t] of bucket.shadow) L.push(`  --${name}: ${resolveCss(v(t), tokens)};`);
  L.push(`}`);

  // 真源深色差异（border-width-independent 等）
  const darkDim = Object.entries(tokens)
    .filter(([n, t]) => t.$extensions?.gts?.dark && t.$type === 'dimension');
  if (darkDim.length) {
    L.push(`[data-theme="dark"] {`);
    for (const [name, t] of darkDim) L.push(`  --${name}: ${t.$extensions.gts.dark};`);
    L.push(`}`);
  }
  return L.join('\n') + '\n';
}

// ---------- semantic.css ----------
// 语义分类按 extract 时的源顺序自然分组；这里按名前缀重排为语义可读顺序。
const SEMANTIC_ORDER = [
  'color-brand', 'color-text-', 'color-icon-', 'color-border', 'color-bg-',
  'color-hover', 'color-select', 'color-table-', 'color-fill',
  'color-error', 'color-alert', 'color-warning', 'color-success', 'color-info', 'color-none',
];

function semanticRank(name) {
  for (let i = 0; i < SEMANTIC_ORDER.length; i++) {
    if (name.startsWith(SEMANTIC_ORDER[i])) return i;
  }
  return 999;
}

function genSemantic(tokens, sourceVersion) {
  const semantic = Object.entries(tokens)
    .filter(([n, t]) =>
      n.startsWith('color-') && !n.startsWith('color-chart') &&
      !t.$extensions?.gts?.hljs && t.$type === 'color')
    .sort((a, b) => semanticRank(a[0]) - semanticRank(b[0]) || a[0].localeCompare(b[0]));

  const L = [];
  L.push(HEADER(sourceVersion));
  L.push(`/* 语义层：业务代码只引用本层（--color-*）。浅色为默认主题；
   [data-theme="dark"] 为工程回填（G 1.5.1 旧版值，设计师 2026-09-16 答复"用旧版值"），设计师正式修订后由 md 行取代。 */`);
  L.push(`:root,\n[data-theme="light"] {`);
  L.push(`  color-scheme: light;`);
  for (const [name, t] of semantic) L.push(semanticLine(name, t));
  L.push(`}`);

  // 深色覆盖：gts.dark = 设计真源（code-*）或工程回填（semantic-dark，darkSource 标注）
  const dark = semantic.filter(([, t]) => t.$extensions?.gts?.dark);
  if (dark.length) {
    L.push(`[data-theme="dark"] {`);
    L.push(`  color-scheme: dark;`);
    for (const [name, t] of dark) L.push(`  --${name}: ${darkCssValue(t)};`);
    L.push(`}`);
  }
  return L.join('\n') + '\n';
}

// 深色值出 CSS：别名 {x} → var(--x)；var(--x) 字面直接透传（回填种子原样）；rgba 字面直落
function darkCssValue(t) {
  const raw = t.$extensions.gts.dark;
  if (typeof raw !== 'string') return String(raw);
  const m = raw.match(/^\{(.+)\}$/);
  if (m) return cssRef(m[1]);
  return raw;
}

// ---------- charts.css ----------
// 源引用常量（GTS 2.2 图表节明文，非 token 表行）：尾部色 blue-70 + 延展三组合。
const CHART_TAIL = 'blue-70';
const CHART_EXTENSIONS = [
  ['extension-1', ['mint-50', 'indigo-40', 'cyan-50', 'purple-40']],
  ['extension-2', ['indigo-50', 'yellow-40', 'blue-50', 'green-40']],
  ['extension-3', ['purple-50', 'green-40', 'cyan-50', 'orange-40']],
];

function genCharts(tokens, sourceVersion) {
  const charts = [];
  for (let i = 1; i <= 6; i++) charts.push(tokens[`color-chart-${i}`]);
  const acc = charts.map((t) => t.$extensions.gts.accessible.slice(1, -1)); // {blue-60} → blue-60

  const L = [];
  L.push(HEADER(sourceVersion));
  L.push(`/* 图表配色：默认六色 + 无障碍组 + 延展组合。选组用 data-chart-palette；两组间不逐色拼接。 */`);
  L.push(`:root,\n[data-chart-palette="default"] {`);
  charts.forEach((t, i) => L.push(`  --color-chart-${i + 1}: ${cssRef(v(t).slice(1, -1))};`));
  L.push(`  --color-chart-tail: ${cssRef(CHART_TAIL)};`);
  acc.forEach((ref, i) => L.push(`  --color-chart-accessible-${i + 1}: ${cssRef(ref)};`));
  CHART_EXTENSIONS.forEach(([label, refs]) =>
    refs.forEach((ref, i) => L.push(`  --color-chart-extension-${label.slice(-1)}-${i + 1}: ${cssRef(ref)};`)));
  L.push(`}`);
  L.push(`[data-chart-palette="accessible"] {`);
  charts.forEach((t, i) => L.push(`  --color-chart-${i + 1}: ${cssRef(acc[i])};`));
  L.push(`}`);
  for (const [label, refs] of CHART_EXTENSIONS) {
    L.push(`[data-chart-palette="${label}"] {`);
    for (let i = 0; i < 6; i++) {
      L.push(`  --color-chart-${i + 1}: ${refs[i] ? cssRef(refs[i]) : 'initial'};`);
    }
    L.push(`}`);
  }
  return L.join('\n') + '\n';
}

// ---------- code.css ----------
function genCode(tokens, sourceVersion) {
  const code = Object.entries(tokens).filter(([n, t]) => !!t.$extensions?.gts?.hljs);
  const L = [];
  L.push(HEADER(sourceVersion));
  L.push(`/* 代码高亮（StarCode）：仅代码展示/编辑场景。浅色默认；深色为设计真源值。 */`);
  L.push(`:root,\n[data-theme="light"] {`);
  for (const [name, t] of code) L.push(`  --${name}: ${t.$value};`);
  L.push(`}`);
  L.push(`[data-theme="dark"] {`);
  for (const [name, t] of code) L.push(`  --${name}: ${t.$extensions.gts.dark};`);
  L.push(`}`);
  return L.join('\n') + '\n';
}

// ---------- frost.css ----------
// 种子 token 直出 + 规则层。规则层是调用约定的实现（data-material 等），
// 值全部 var() 引用 token；token 名与旧 frosted.css 兼容（--frost-blur-* 等），
// 设计师补齐正式表后 extract 解析同名 token 自动接管。
// 浅/深同名的扁平 token（alpha/surface/shadow/tint/backdrop/solid/border/neutral-rgb）：
// $value 为浅色（:root 默认主题），gts.dark 为深色（data-theme="dark" 覆盖）。
function genFrost(tokens, sourceVersion) {
  const frost = Object.entries(tokens).filter(([n, t]) => t.$extensions?.gts?.source === 'backfill-g1.5.1');
  const byGroup = (g) => frost.filter(([, t]) => t.$extensions.gts.group === g);

  const line = (name, t) => {
    const raw = t.$value;
    const out = typeof raw === 'string' && /^\{.+\}$/.test(raw) ? cssRef(raw.slice(1, -1)) : raw;
    return `  --${name}: ${out};`;
  };

  const L = [];
  L.push(HEADER(sourceVersion));
  L.push(`/* 毛玻璃（过渡基线）：数值为 G 1.5.1 已验证实现回填，待设计师复核（见 设计系统.md §7）。
   Token 层 :root 段由管线生成；规则层实现 §7.7 调用约定（data-material 协议）。 */`);

  // 全部种子（common + light + decoration）：:root 默认主题
  L.push(`:root {`);
  for (const [name, t] of frost) L.push(line(name, t));
  L.push(`}`);
  // 真源深色差异（gts.dark）→ data-theme="dark" 覆盖
  const darkPairs = frost.filter(([, t]) => t.$extensions?.gts?.dark);
  if (darkPairs.length) {
    L.push(`[data-theme="dark"] {`);
    for (const [name, t] of darkPairs) L.push(`  --${name}: ${t.$extensions.gts.dark};`);
    L.push(`}`);
  }

  // 规则层：值全部引用 token，与旧 frosted.css/frost-decoration.css 行为一致（g-glass-* 遗留选择器已移除）
  L.push(`/* ---- 规则层：§7.7 调用约定实现 ---- */`);
  L.push(FROST_RULES);
  return L.join('\n') + '\n';
}

const FROST_RULES = `/* Apply backdrop color to a separate parent, never to the frosted surface itself. */
.g-frost-backdrop {
  background-color: var(--frost-backdrop-base);
  background-image: var(--frost-backdrop-gradient);
}
:is([data-material="frosted"]) {
  --_frost-blur: var(--frost-blur-card);
  --_frost-alpha: var(--frost-alpha-card);
  --_frost-surface: var(--frost-surface-card);
  --_frost-shadow: var(--frost-shadow-card);
  --_frost-tint: transparent;
  --_frost-saturate: var(--frost-saturate-neutral);
  background-color: var(--_frost-surface);
  background-image: linear-gradient(var(--_frost-tint), var(--_frost-tint));
  border: var(--frost-border-width) solid var(--frost-border);
  box-shadow: var(--_frost-shadow);
  -webkit-backdrop-filter: blur(var(--_frost-blur)) saturate(var(--_frost-saturate));
  backdrop-filter: blur(var(--_frost-blur)) saturate(var(--_frost-saturate));
}
[data-material="frosted"][data-frost-level="control"] {
  --_frost-blur: var(--frost-blur-control);
  --_frost-alpha: var(--frost-alpha-control);
  --_frost-surface: var(--frost-surface-control);
  --_frost-shadow: var(--frost-shadow-control);
}
[data-material="frosted"][data-frost-level="overlay"] {
  --_frost-blur: var(--frost-blur-overlay);
  --_frost-alpha: var(--frost-alpha-overlay);
  --_frost-surface: var(--frost-surface-overlay);
  --_frost-shadow: var(--frost-shadow-overlay);
}
[data-material="frosted"][data-frost-tint="blue"] { --_frost-tint: var(--frost-tint-blue); }
[data-material="frosted"][data-frost-tint="lavender"] { --_frost-tint: var(--frost-tint-lavender); }
[data-material="frosted"][data-frost-tint="teal"] { --_frost-tint: var(--frost-tint-teal); }
[data-material="frosted"][data-frost-tone="muted"] { --_frost-saturate: var(--frost-saturate-muted); }
[data-material="frosted"]:is(button, a, [role="button"], [data-frost-interactive="true"]) {
  transition: background-color var(--frost-transition-duration) var(--frost-transition-easing), box-shadow var(--frost-transition-duration) var(--frost-transition-easing);
}
[data-material="frosted"]:is(button, a, [role="button"], [data-frost-interactive="true"]):hover:not(:disabled):not([aria-disabled="true"]) {
  background-color: rgba(var(--frost-neutral-rgb), calc(var(--_frost-alpha) + var(--frost-alpha-hover-delta)));
}
[data-material="frosted"]:is(button, a, [role="button"], [data-frost-interactive="true"]):active:not(:disabled):not([aria-disabled="true"]) {
  background-color: rgba(var(--frost-neutral-rgb), calc(var(--_frost-alpha) + var(--frost-alpha-active-delta)));
  box-shadow: none;
}
[data-material="frosted"]:focus-visible {
  outline: var(--border-width-medium) solid var(--color-border-focus);
  outline-offset: var(--border-width-medium);
}
[data-material="frosted"]:is([aria-selected="true"], [aria-pressed="true"]) { border-color: var(--color-border-focus); }
[data-material="frosted"]:is(:disabled, [aria-disabled="true"]) {
  background-color: var(--color-fill-disabled);
  background-image: none;
  color: var(--color-text-disabled);
  border-color: var(--color-border-disabled);
  box-shadow: none;
  -webkit-backdrop-filter: none;
  backdrop-filter: none;
}
/* A nested surface may use fill but must not add a second background blur. */
[data-material="frosted"] [data-material="frosted"] {
  -webkit-backdrop-filter: none !important;
  backdrop-filter: none !important;
}
@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {
  [data-material="frosted"] {
    background-color: var(--frost-surface-solid) !important;
    -webkit-backdrop-filter: none !important;
    backdrop-filter: none !important;
  }
}
@media (prefers-reduced-transparency: reduce) {
  [data-material="frosted"] {
    background-color: var(--frost-surface-solid) !important;
    -webkit-backdrop-filter: none !important;
    backdrop-filter: none !important;
  }
}
[data-transparency="reduced"] [data-material="frosted"],
[data-material="frosted"][data-transparency="reduced"] {
  background-color: var(--frost-surface-solid) !important;
  -webkit-backdrop-filter: none !important;
  backdrop-filter: none !important;
}
@media (prefers-reduced-motion: reduce) {
  [data-material="frosted"] { transition: none !important; }
}
@media (forced-colors: active) {
  [data-material="frosted"] {
    background: Canvas !important;
    color: CanvasText;
    border-color: ButtonText;
    box-shadow: none;
    -webkit-backdrop-filter: none !important;
    backdrop-filter: none !important;
  }
}

/* ---- 品牌色块磨砂装饰（§7.6，data-decoration 协议） ---- */
[data-surface="brand"]:not([data-material="frosted"]) {
  background-color: var(--frost-decor-brand-start);
  background-image: var(--frost-decor-brand-gradient);
  color: var(--frost-decor-ink);
  border-color: transparent;
}
[data-decoration="frosted"] {
  --_frost-decor-scale: var(--frost-decor-scale-card);
  position: relative;
  overflow: hidden;
  isolation: isolate;
}
[data-decoration="frosted"][data-decoration-size="panel"] { --_frost-decor-scale: var(--frost-decor-scale-panel); }
[data-decoration="frosted"] > * { position: relative; z-index: 1; }
[data-decoration="frosted"]::before,
[data-decoration="frosted"]::after {
  content: "";
  position: absolute;
  pointer-events: none;
  z-index: 0;
  aspect-ratio: 1;
  box-sizing: border-box;
  border: var(--border-width-normal) solid var(--frost-decor-border);
  background-image: var(--frost-decor-shape-gradient);
  -webkit-backdrop-filter: blur(var(--frost-decor-blur));
  backdrop-filter: blur(var(--frost-decor-blur));
}
[data-decoration="frosted"]::before {
  width: min(calc(var(--frost-decor-circle-size) * var(--_frost-decor-scale)), 52%);
  top: calc(var(--frost-decor-circle-top) * var(--_frost-decor-scale));
  right: calc(var(--frost-decor-circle-right) * var(--_frost-decor-scale));
  border-radius: 50%;
}
[data-decoration="frosted"]::after {
  width: min(calc(var(--frost-decor-tile-size) * var(--_frost-decor-scale)), 32%);
  top: calc(var(--frost-decor-tile-top) * var(--_frost-decor-scale));
  right: calc(var(--frost-decor-tile-right) * var(--_frost-decor-scale));
  border-radius: var(--frost-decor-tile-radius);
  transform: rotate(var(--frost-decor-tile-rotation));
}
/* A small control or an already blurred surface never receives another blur layer. */
:is(button, a, input, select, textarea, th, td)[data-decoration="frosted"]::before,
:is(button, a, input, select, textarea, th, td)[data-decoration="frosted"]::after,
[data-material="frosted"][data-decoration="frosted"]::before,
[data-material="frosted"][data-decoration="frosted"]::after,
[data-material="frosted"] [data-decoration="frosted"]::before,
[data-material="frosted"] [data-decoration="frosted"]::after,
[data-decoration="frosted"] [data-decoration="frosted"]::before,
[data-decoration="frosted"] [data-decoration="frosted"]::after,
[data-decoration="frosted"][aria-disabled="true"]::before,
[data-decoration="frosted"][aria-disabled="true"]::after { display: none; }
@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {
  [data-decoration="frosted"]::before, [data-decoration="frosted"]::after { display: none; }
}
@media (prefers-reduced-transparency: reduce) {
  [data-decoration="frosted"]::before, [data-decoration="frosted"]::after { display: none; }
}
[data-transparency="reduced"] [data-decoration="frosted"]::before,
[data-transparency="reduced"] [data-decoration="frosted"]::after,
[data-decoration="frosted"][data-transparency="reduced"]::before,
[data-decoration="frosted"][data-transparency="reduced"]::after { display: none; }
@media (forced-colors: active) {
  [data-surface="brand"]:not([data-material="frosted"]) { background: Canvas; color: CanvasText; border-color: ButtonText; }
  [data-decoration="frosted"]::before, [data-decoration="frosted"]::after { display: none; }
}`;

// ---------- element-plus.css ----------
// 桥接层："手写一次不再动"（拍板口径）——脚本只核对引用面，不重写规则。
// 这里保存的是 v2.2 基线桥（与旧文件差异：g-control-radius/g-control-height 改为直连新 token；
// 删除 --g-* 中转与 portal-highlight/g-shadow 两个旧库独有名）。
const EP_BRIDGE = `/* EP 桥：Element Plus 组件内部读 --el-*（官方换肤机制）。全仓唯一一份；手写锚点，generate 不重写规则段。
   先加载 Element Plus 基础样式，再加载本目录 tokens/index.css。 */
:root,
[data-theme] {
  --el-color-primary: var(--color-brand);
  --el-color-primary-light-3: var(--color-brand-hover);
  --el-color-primary-light-5: var(--color-brand-disabled);
  --el-color-primary-light-7: var(--brand-10);
  --el-color-primary-light-8: var(--color-select);
  --el-color-primary-light-9: var(--color-select);
  --el-color-primary-dark-2: var(--color-brand-active);
  --el-bg-color-page: var(--color-bg-1);
  --el-bg-color: var(--color-bg-5);
  --el-bg-color-overlay: var(--color-bg-4);
  --el-text-color-primary: var(--color-text-primary);
  --el-text-color-regular: var(--color-text-primary);
  --el-text-color-secondary: var(--color-text-secondary);
  --el-text-color-placeholder: var(--color-text-placeholder);
  --el-text-color-disabled: var(--color-text-disabled);
  --el-border-color: var(--color-border);
  --el-border-color-light: var(--color-border-separator);
  --el-border-color-lighter: var(--color-border-separator-subtle);
  --el-border-color-extra-light: var(--color-border-separator-subtle);
  --el-border-color-dark: var(--color-border-hover);
  --el-border-color-darker: var(--color-border-hover);
  --el-border-color-hover: var(--color-border-hover);
  --el-fill-color: var(--color-fill);
  --el-fill-color-light: var(--color-hover);
  --el-fill-color-lighter: var(--color-table-zebra);
  --el-fill-color-extra-light: var(--color-fill-subtle);
  --el-fill-color-dark: var(--color-fill-disabled);
  --el-fill-color-darker: var(--color-fill-disabled);
  --el-fill-color-blank: var(--color-fill-subtle);
  --el-mask-color: var(--color-bg-mask);
  --el-mask-color-extra-light: var(--color-bg-mask);
  --el-overlay-color: var(--color-bg-mask);
  --el-overlay-color-light: var(--color-bg-mask);
  --el-overlay-color-lighter: var(--color-bg-mask);
  --el-disabled-bg-color: var(--color-fill-disabled-subtle);
  --el-disabled-text-color: var(--color-text-disabled);
  --el-disabled-border-color: var(--color-border-disabled);
  --el-border-radius-base: var(--radius-size-normal);
  --el-component-size: 32px;
  --el-color-success: var(--color-success);
  --el-color-success-light-3: var(--mint-40);
  --el-color-success-light-5: var(--mint-20);
  --el-color-success-light-7: var(--mint-10);
  --el-color-success-light-8: var(--color-success-subtle);
  --el-color-success-light-9: var(--color-success-subtle);
  --el-color-success-dark-2: var(--mint-60);
  --el-color-warning: var(--color-warning);
  --el-color-warning-light-3: var(--yellow-40);
  --el-color-warning-light-5: var(--yellow-20);
  --el-color-warning-light-7: var(--yellow-10);
  --el-color-warning-light-8: var(--color-warning-subtle);
  --el-color-warning-light-9: var(--color-warning-subtle);
  --el-color-warning-dark-2: var(--yellow-60);
  --el-color-danger: var(--color-error);
  --el-color-danger-light-3: var(--red-40);
  --el-color-danger-light-5: var(--red-20);
  --el-color-danger-light-7: var(--red-10);
  --el-color-danger-light-8: var(--color-error-subtle);
  --el-color-danger-light-9: var(--color-error-subtle);
  --el-color-danger-dark-2: var(--red-60);
  --el-color-error: var(--color-error);
  --el-color-error-light-3: var(--red-40);
  --el-color-error-light-5: var(--red-20);
  --el-color-error-light-7: var(--red-10);
  --el-color-error-light-8: var(--color-error-subtle);
  --el-color-error-light-9: var(--color-error-subtle);
  --el-color-error-dark-2: var(--red-60);
  --el-color-info: var(--color-info);
  --el-color-info-light-3: var(--blue-40);
  --el-color-info-light-5: var(--blue-20);
  --el-color-info-light-7: var(--blue-10);
  --el-color-info-light-8: var(--color-info-subtle);
  --el-color-info-light-9: var(--color-info-subtle);
  --el-color-info-dark-2: var(--blue-60);
  --el-font-family: var(--font-family-zh);
}
.el-button--primary {
  --el-button-hover-bg-color: var(--color-brand-hover);
  --el-button-hover-border-color: var(--color-brand-hover);
  --el-button-active-bg-color: var(--color-brand-active);
  --el-button-active-border-color: var(--color-brand-active);
  --el-button-disabled-bg-color: var(--color-brand-disabled);
  --el-button-disabled-border-color: var(--color-brand-disabled);
}
.el-button--primary.is-plain {
  --el-button-bg-color: var(--color-select);
  --el-button-hover-bg-color: var(--color-brand-hover);
  --el-button-hover-border-color: var(--color-brand-hover);
  --el-button-disabled-bg-color: var(--color-fill-disabled-subtle);
  --el-button-disabled-border-color: var(--color-border-disabled);
}
.el-button--warning {
  --el-button-text-color: var(--gray-90);
  --el-button-hover-text-color: var(--gray-90);
  --el-button-active-text-color: var(--gray-90);
}
.el-tag.el-tag--warning {
  --el-tag-text-color: var(--color-text-primary);
}
.el-input,
.el-textarea,
.el-select {
  --el-input-hover-border-color: var(--color-border-hover);
  --el-input-focus-border-color: var(--color-border-focus);
  --el-input-bg-color: var(--color-fill-subtle);
  --el-select-input-focus-border-color: var(--color-border-focus);
  --el-select-border-color-hover: var(--color-border-hover);
}
.el-table {
  --el-table-header-bg-color: var(--color-table-header);
  --el-table-row-hover-bg-color: var(--color-hover);
  --el-table-current-row-bg-color: var(--color-select);
  --el-table-border-color: var(--color-border);
  --el-table-header-text-color: var(--color-text-primary);
}
.el-table--striped .el-table__body tr.el-table__row--striped td.el-table__cell { background: var(--color-table-zebra); }`;

// bridge 核对：EP 桥里引用的每个 var 名必须存在于 primitive/semantic 产物中
function checkBridge(bridgeVars, defined) {
  const missing = bridgeVars.filter((n) => !defined.has(`--${n}`));
  return missing;
}

function collectBridgeVars(bridgeText) {
  const out = new Set();
  for (const m of bridgeText.matchAll(/var\(--([a-z0-9-]+)\)/g)) out.add(m[1]);
  return [...out];
}

// ---------- index.css ----------
const INDEX_FILES = ['primitive.css', 'semantic.css', 'charts.css', 'code.css', 'frost.css', 'element-plus.css'];

function genIndex(sourceVersion) {
  const L = [];
  L.push(HEADER(sourceVersion));
  L.push(`/* 加载顺序：primitive（字面值）→ semantic（语义链）→ charts/code/frost（专项）→ element-plus（桥）。 */`);
  for (const f of INDEX_FILES) L.push(`@import "./${f}";`);
  return L.join('\n') + '\n';
}

// ---------- main ----------
const args = parseArgs(process.argv);
if (!args.tokens || !args.out) {
  console.error('Usage: node generate-css.mjs --tokens <tokens.json> --out <dir> [--check-only]');
  process.exit(1);
}

const data = JSON.parse(readFileSync(args.tokens, 'utf8'));
const tokens = data.tokens;
const sourceVersion = data.meta?.sourceVersion || data.meta?.['source-version'] || 'unversioned';

const pieces = {
  'primitive.css': genPrimitive(tokens, sourceVersion),
  'semantic.css': genSemantic(tokens, sourceVersion),
  'charts.css': genCharts(tokens, sourceVersion),
  'code.css': genCode(tokens, sourceVersion),
  'frost.css': genFrost(tokens, sourceVersion),
  'element-plus.css': EP_BRIDGE + '\n',
  'index.css': genIndex(sourceVersion),
};

// 核对：EP 桥 + 规则层引用的 var 全部有定义（禁造未定义值的 CSS 版）
const defined = new Set();
for (const [file, text] of Object.entries(pieces)) {
  if (file === 'element-plus.css' || file === 'index.css') continue;
  for (const m of text.matchAll(/^\s*--([A-Za-z0-9-]+)\s*:/gm)) defined.add(`--${m[1]}`);
}
const bridgeVars = collectBridgeVars(pieces['element-plus.css']);
const missing = checkBridge(bridgeVars, defined);
if (missing.length) {
  console.error(`BRIDGE-ERROR: EP 桥引用了未定义变量: ${missing.join(', ')}`);
  process.exit(2);
}
// 规则层死链扫描：所有 var() 引用必须可解析（var 名限 kebab-case 小写，含大写即为旧名残留）
const ruleTexts = Object.entries(pieces).filter(([f]) => f !== 'index.css');
const deadLinks = [];
for (const [file, text] of ruleTexts) {
  for (const m of text.matchAll(/var\(--([A-Za-z0-9-]+)\)/g)) {
    if (!defined.has(`--${m[1]}`)) deadLinks.push(`${file}: var(--${m[1]})`);
  }
}
if (deadLinks.length) {
  console.error(`DEAD-LINK: 生成产物存在未定义引用:\n  ${[...new Set(deadLinks)].join('\n  ')}`);
  process.exit(3);
}

if (args['check-only']) {
  console.log('check-only: bridge vars all defined ✓');
  process.exit(0);
}

mkdirSync(args.out, { recursive: true });
for (const [file, text] of Object.entries(pieces)) {
  writeFileSync(path.join(args.out, file), text, 'utf8');
}

// 报告：深色覆盖统计
const darkCount = Object.values(tokens).filter((t) => t.$extensions?.gts?.dark).length;
const darkBackfill = Object.values(tokens).filter((t) => t.$extensions?.gts?.darkSource === 'backfill-g1.5.1').length;
console.log(`generated ${Object.keys(pieces).length} files → ${args.out}`);
console.log(`  dark overrides: ${darkCount} tokens (工程回填 ${darkBackfill})`);
console.log(`  frost seed: ${Object.values(tokens).filter((t) => t.$extensions?.gts?.source === 'backfill-g1.5.1').length} tokens (backfill-g1.5.1)`);
console.log(`  bridge check: ${bridgeVars.length} vars, all defined ✓`);
